2025-02-10 18:42:44.675 | INFO     | __main__:<module>:39 - Logging to file: logs\project_log.log
2025-02-10 18:42:44.676 | INFO     | __main__:main:61 - STARTING utils_logger.py
2025-02-10 18:42:44.676 | INFO     | __main__:log_example:52 - This is an example info message.
2025-02-10 18:42:44.676 | WARNING  | __main__:log_example:53 - This is an example warning message.
2025-02-10 18:42:44.676 | ERROR    | __main__:log_example:54 - This is an example error message.
2025-02-10 18:42:44.677 | INFO     | __main__:main:66 - View the log output at logs\project_log.log
2025-02-10 18:42:44.677 | INFO     | __main__:main:67 - EXITING utils_logger.py.
2025-02-10 18:55:17.162 | INFO     | __main__:<module>:39 - Logging to file: logs\project_log.log
2025-02-10 18:55:17.162 | INFO     | __main__:main:61 - STARTING utils_logger.py
2025-02-10 18:55:17.163 | INFO     | __main__:log_example:52 - This is an example info message.
2025-02-10 18:55:17.163 | WARNING  | __main__:log_example:53 - This is an example warning message.
2025-02-10 18:55:17.163 | ERROR    | __main__:log_example:54 - This is an example error message.
2025-02-10 18:55:17.163 | INFO     | __main__:main:66 - View the log output at logs\project_log.log
2025-02-10 18:55:17.164 | INFO     | __main__:main:67 - EXITING utils_logger.py.
2025-02-10 20:36:48.624 | INFO     | utils_logger:<module>:39 - Logging to file: logs\project_log.log
2025-02-10 20:36:48.625 | INFO     | __main__:main:38 - Starting database setup...
2025-02-10 20:36:48.626 | INFO     | __main__:main:52 - Connected to database: C:\Projects\datafun-05-sql\data\db.sqlite
2025-02-10 20:36:48.626 | ERROR    | __main__:execute_sql_file:32 - Failed to execute C:\Projects\datafun-05-sql\sql_create\01_drop_tables.sql: [Errno 2] No such file or directory: 'C:\\Projects\\datafun-05-sql\\sql_create\\01_drop_tables.sql'
2025-02-10 20:36:48.627 | ERROR    | __main__:main:62 - Error during database setup: [Errno 2] No such file or directory: 'C:\\Projects\\datafun-05-sql\\sql_create\\01_drop_tables.sql'
2025-02-10 20:36:48.629 | INFO     | __main__:main:65 - Database connection closed.
2025-02-10 20:37:40.379 | INFO     | __main__:<module>:39 - Logging to file: logs\project_log.log
2025-02-10 20:37:40.380 | INFO     | __main__:main:61 - STARTING utils_logger.py
2025-02-10 20:37:40.380 | INFO     | __main__:log_example:52 - This is an example info message.
2025-02-10 20:37:40.380 | WARNING  | __main__:log_example:53 - This is an example warning message.
2025-02-10 20:37:40.380 | ERROR    | __main__:log_example:54 - This is an example error message.
2025-02-10 20:37:40.380 | INFO     | __main__:main:66 - View the log output at logs\project_log.log
2025-02-10 20:37:40.381 | INFO     | __main__:main:67 - EXITING utils_logger.py.
2025-02-10 20:37:45.609 | INFO     | utils_logger:<module>:39 - Logging to file: logs\project_log.log
2025-02-10 20:37:45.609 | INFO     | __main__:main:38 - Starting database setup...
2025-02-10 20:37:45.610 | INFO     | __main__:main:52 - Connected to database: C:\Projects\datafun-05-sql\data\db.sqlite
2025-02-10 20:37:45.611 | ERROR    | __main__:execute_sql_file:32 - Failed to execute C:\Projects\datafun-05-sql\sql_create\01_drop_tables.sql: [Errno 2] No such file or directory: 'C:\\Projects\\datafun-05-sql\\sql_create\\01_drop_tables.sql'
2025-02-10 20:37:45.611 | ERROR    | __main__:main:62 - Error during database setup: [Errno 2] No such file or directory: 'C:\\Projects\\datafun-05-sql\\sql_create\\01_drop_tables.sql'
2025-02-10 20:37:45.611 | INFO     | __main__:main:65 - Database connection closed.
2025-02-10 20:53:46.730 | INFO     | utils_logger:<module>:39 - Logging to file: logs\project_log.log
2025-02-10 20:53:46.730 | INFO     | __main__:main:38 - Starting database setup...
2025-02-10 20:53:46.731 | INFO     | __main__:main:52 - Connected to database: C:\Projects\datafun-05-sql\data\db.sqlite
2025-02-10 20:53:46.731 | ERROR    | __main__:execute_sql_file:32 - Failed to execute C:\Projects\datafun-05-sql\sql_create\01_drop_tables.sql: [Errno 2] No such file or directory: 'C:\\Projects\\datafun-05-sql\\sql_create\\01_drop_tables.sql'
2025-02-10 20:53:46.732 | ERROR    | __main__:main:62 - Error during database setup: [Errno 2] No such file or directory: 'C:\\Projects\\datafun-05-sql\\sql_create\\01_drop_tables.sql'
2025-02-10 20:53:46.732 | INFO     | __main__:main:65 - Database connection closed.
2025-02-10 20:56:35.802 | INFO     | utils_logger:<module>:39 - Logging to file: logs\project_log.log
2025-02-10 20:56:35.803 | INFO     | __main__:main:38 - Starting database setup...
2025-02-10 20:56:35.804 | INFO     | __main__:main:52 - Connected to database: C:\Projects\datafun-05-sql\data\db.sqlite
2025-02-10 20:56:35.804 | ERROR    | __main__:execute_sql_file:32 - Failed to execute C:\Projects\datafun-05-sql\sql_create\01_drop_tables.sql: [Errno 2] No such file or directory: 'C:\\Projects\\datafun-05-sql\\sql_create\\01_drop_tables.sql'
2025-02-10 20:56:35.805 | ERROR    | __main__:main:62 - Error during database setup: [Errno 2] No such file or directory: 'C:\\Projects\\datafun-05-sql\\sql_create\\01_drop_tables.sql'
2025-02-10 20:56:35.805 | INFO     | __main__:main:65 - Database connection closed.
2025-02-10 21:01:05.499 | INFO     | utils_logger:<module>:39 - Logging to file: logs\project_log.log
2025-02-10 21:01:05.500 | INFO     | __main__:main:38 - Starting database setup...
2025-02-10 21:01:05.501 | INFO     | __main__:main:52 - Connected to database: C:\Projects\datafun-05-sql\data\db.sqlite
2025-02-10 21:01:05.502 | INFO     | __main__:execute_sql_file:30 - Executed: C:\Projects\datafun-05-sql\sql_create\01_drop_tables.sql
2025-02-10 21:01:05.511 | INFO     | __main__:execute_sql_file:30 - Executed: C:\Projects\datafun-05-sql\sql_create\02_create_tables.sql
2025-02-10 21:01:05.517 | INFO     | __main__:execute_sql_file:30 - Executed: C:\Projects\datafun-05-sql\sql_create\03_insert_records.sql
2025-02-10 21:01:05.518 | INFO     | __main__:main:60 - Database setup completed successfully.
2025-02-10 21:01:05.518 | INFO     | __main__:main:65 - Database connection closed.
2025-02-10 21:05:57.529 | INFO     | utils_logger:<module>:39 - Logging to file: logs\project_log.log
2025-02-10 21:05:57.530 | INFO     | __main__:main:36 - Starting feature queries execution...
2025-02-10 21:05:57.531 | INFO     | __main__:main:52 - Connected to database: C:\Projects\datafun-05-sql\data\db.sqlite
2025-02-10 21:05:57.531 | INFO     | __main__:main:58 - Feature queries execution completed successfully.
2025-02-10 21:05:57.532 | INFO     | __main__:main:63 - Database connection closed.
2025-02-10 21:06:08.521 | INFO     | utils_logger:<module>:39 - Logging to file: logs\project_log.log
2025-02-10 21:06:08.522 | INFO     | __main__:main:38 - Starting database setup...
2025-02-10 21:06:08.523 | INFO     | __main__:main:52 - Connected to database: C:\Projects\datafun-05-sql\data\db.sqlite
2025-02-10 21:06:08.532 | INFO     | __main__:execute_sql_file:30 - Executed: C:\Projects\datafun-05-sql\sql_create\01_drop_tables.sql
2025-02-10 21:06:08.540 | INFO     | __main__:execute_sql_file:30 - Executed: C:\Projects\datafun-05-sql\sql_create\02_create_tables.sql
2025-02-10 21:06:08.548 | INFO     | __main__:execute_sql_file:30 - Executed: C:\Projects\datafun-05-sql\sql_create\03_insert_records.sql
2025-02-10 21:06:08.548 | INFO     | __main__:main:60 - Database setup completed successfully.
2025-02-10 21:06:08.550 | INFO     | __main__:main:65 - Database connection closed.
2025-02-10 21:06:12.627 | INFO     | utils_logger:<module>:39 - Logging to file: logs\project_log.log
2025-02-10 21:06:12.627 | INFO     | __main__:main:36 - Starting feature queries execution...
2025-02-10 21:06:12.628 | INFO     | __main__:main:52 - Connected to database: C:\Projects\datafun-05-sql\data\db.sqlite
2025-02-10 21:06:12.628 | INFO     | __main__:main:58 - Feature queries execution completed successfully.
2025-02-10 21:06:12.629 | INFO     | __main__:main:63 - Database connection closed.
2025-02-10 21:06:58.631 | INFO     | utils_logger:<module>:39 - Logging to file: logs\project_log.log
2025-02-10 21:06:58.631 | INFO     | __main__:main:36 - Starting feature queries execution...
2025-02-10 21:06:58.632 | INFO     | __main__:main:52 - Connected to database: C:\Projects\datafun-05-sql\data\db.sqlite
2025-02-10 21:06:58.633 | INFO     | __main__:main:58 - Feature queries execution completed successfully.
2025-02-10 21:06:58.633 | INFO     | __main__:main:63 - Database connection closed.
2025-02-10 21:14:04.380 | INFO     | utils_logger:<module>:39 - Logging to file: logs\project_log.log
2025-02-10 21:14:04.380 | INFO     | __main__:main:36 - Starting feature queries execution...
2025-02-10 21:14:04.381 | INFO     | __main__:main:52 - Connected to database: C:\Projects\datafun-05-sql\data\db.sqlite
2025-02-10 21:14:04.382 | INFO     | __main__:main:58 - Feature queries execution completed successfully.
2025-02-10 21:14:04.382 | INFO     | __main__:main:63 - Database connection closed.
2025-02-10 21:15:33.397 | INFO     | utils_logger:<module>:39 - Logging to file: logs\project_log.log
2025-02-10 21:15:33.398 | INFO     | __main__:main:36 - Starting feature queries execution...
2025-02-10 21:15:33.399 | INFO     | __main__:main:52 - Connected to database: C:\Projects\datafun-05-sql\data\db.sqlite
2025-02-10 21:15:33.399 | INFO     | __main__:main:58 - Feature queries execution completed successfully.
2025-02-10 21:15:33.400 | INFO     | __main__:main:63 - Database connection closed.
2025-02-10 21:18:18.433 | INFO     | utils_logger:<module>:39 - Logging to file: logs\project_log.log
2025-02-10 21:18:18.433 | INFO     | __main__:main:36 - Starting feature queries execution...
2025-02-10 21:18:18.434 | INFO     | __main__:main:52 - Connected to database: C:\Projects\datafun-05-sql\data\db.sqlite
2025-02-10 21:18:18.435 | INFO     | __main__:main:58 - Feature queries execution completed successfully.
2025-02-10 21:18:18.435 | INFO     | __main__:main:63 - Database connection closed.
